import Head from "next/head";
import Navbar from "../Components/Navbar/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shortly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
    </div>
  );
}
